name: Build # The name of the pipeline
on: # When the pipeline will run
    push: # The pipeline will run whenever new code is pushed on every branch
    pull_request: # The pipeline will also run whenever a pull request is made

jobs:
  gradle: # The name of the job in the pipeline
    runs-on: ubuntu-latest # The virtual machine Operating System that will run the pipeline
    steps: # The steps that the pipeline will take
    - name: Clone/checkout repository # Clones the GitHub Repository code onto the virtual machine
      uses: actions/checkout@v3 # Using the actions/checkout template

    - name: Setup Java # Sets up and installs Java on the virtual machine
      uses: actions/setup-java@v3 # Using the actions/setup-java template
      with:
        java-version: '17' # Use Java 17
        distribution: 'adopt' # Use the Adopt version of Java

    - name: Setup Gradle # Sets up and installs Gradle on the virtual machine
      uses: gradle/gradle-build-action@v2 # Using the gradle/gradle-build-action template

    - name: Chmod Gradlew # Changes the permissions of the Gradle wrapper
      run: chmod +x gradlew # Allows the Gradle wrapper to be executed

    - name: Run Unit Tests # Executes the unit tests
      run: ./gradlew test

    - name: Execute Gradle build # Executes the Gradle build
      run: ./gradlew build